// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2811.RecycleRush.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2811.RecycleRush.Robot;


/**
 * DEPRECIATED. For manual control, use BidentDownManual
 */
public class  BidentDown extends Command {
	public double TOTE = 12;
	public double GAP = 2;
	public double GRAB = 12;
	public double GAPPOSITIONONE = TOTE + GAP;
	public double GAPPOSITIONTWO = 2*TOTE + GAP;
	public double GAPPOSITIONTHREE = 3*TOTE + GAP;
	public double GAPPOSITIONFOUR = 4*TOTE + GAP;
	public double GAPPOSITIONFIVE = 5*TOTE + GAP;
	public double GAPPOSITIONSIX = 6*TOTE + GAP;
	
    public BidentDown() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

    	System.out.println(Robot.bident.getTotes());
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.logger.setDebug(true);
    	Robot.logger.debug("bident tote down init");
	    Robot.logger.debug(""+Robot.bident.getTotes());
	    Robot.bident.setOneToteDown();
	    System.out.println(Robot.bident.getTotes());
	    Robot.logger.debug(""+Robot.bident.getTotes());
    }

   
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	return true;
    }

    // Called once after isFinished returns true
    protected void end() {
    	System.out.println(Robot.bident.getTotes());
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
