// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2811.RecycleRush.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2811.RecycleRush.Robot;

/**hooks the tote and move the totes up one tote step
 *
 */
public class  RollersInUntil extends Command {
	private static double inches=0;
	
    
    /**
     * Turn on rollers until we hit the switch
     */
    public RollersInUntil() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

	/**
	 * Turn on rollers until we hit a target range
	 * @param inches
	 */
    public RollersInUntil(double range_inches) {
    	inches=range_inches;
    }
    
    // Called just before this Command runs the first time
    protected void initialize() {
    	System.out.println("Rolling in until tote");
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.toteIntake.rollersIn();
    	System.out.println("Rollers on!");
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	//switch is at the target distance
    	 if(inches !=0 && Robot.toteElevator.getDistanceToTote()<inches){
    		 return true;
    	 }
    	
    	//switch is hit
    	return Robot.toteElevator.switchIsPressed();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.toteIntake.rollersOff();
    	System.out.println("Tote acquired");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
