// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2811.RecycleRush;

import org.usfirst.frc2811.RecycleRush.commands.*;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	private double jdXMap=.7;
	private double jdYMap=.7;
	private double jdZMap=.7;
	
	private double austinXMap=.7;
	private double austinYMap=.7;
	private double austinZMap=.7;
	
	private double testingXMap=.5;
	private double testingYMap=.5;
	private double testingZMap=.5;
	
	private double threeAxisXMap=.7;
	private double threeAxisYMap=.7;
	private double threeAxisZMap=.3;
	
	
	
	public static String driver="twodriver";

	public Joystick gamePad;
	    public JoystickButton buttonG1 ;
		public JoystickButton buttonG2 ;
		public JoystickButton buttonG3 ;
		public JoystickButton buttonG4 ;
		public JoystickButton buttonG5 ;
		public JoystickButton buttonG6 ;
		public JoystickButton buttonG7 ;
		public JoystickButton buttonG8 ;
		public JoystickButton buttonG9 ;
		public JoystickButton buttonG10;
		
	public Joystick leftStick;
		public JoystickButton buttonL1 ;
		public JoystickButton buttonL2 ;
		public JoystickButton buttonL3 ;
		public JoystickButton buttonL4 ;
		public JoystickButton buttonL5 ;
		public JoystickButton buttonL6 ;
		public JoystickButton buttonL7 ;
		public JoystickButton buttonL8 ;
		public JoystickButton buttonL9 ;
		public JoystickButton buttonL10;
    
    public Joystick rightStick;
	    public JoystickButton buttonR1 ;
		public JoystickButton buttonR2 ;
		public JoystickButton buttonR3 ;
		public JoystickButton buttonR4 ;
		public JoystickButton buttonR5 ;
		public JoystickButton buttonR6 ;
		public JoystickButton buttonR7 ;
		public JoystickButton buttonR8 ;
		public JoystickButton buttonR9 ;
		public JoystickButton buttonR10;
    	
    public Joystick threeAxis;
	    public JoystickButton buttonT1 ;
		public JoystickButton buttonT2 ;
		public JoystickButton buttonT3 ;
		public JoystickButton buttonT4 ;
		public JoystickButton buttonT5 ;
		public JoystickButton buttonT6 ;
		public JoystickButton buttonT7 ;
		public JoystickButton buttonT8 ;
		public JoystickButton buttonT9 ;
		public JoystickButton buttonT10;
		public JoystickButton buttonT11;
		public JoystickButton buttonT12;
	
    public double getAxisForward(){
        switch(driver.toLowerCase()){
    		case "jd":	
    			return map(gamePad.getY(),1,-1,jdYMap,-jdYMap);
    		case "austin":	
    			return map(leftStick.getY(),1,-1,austinYMap,-austinYMap);
    		case "twodriver":
    			return map(leftStick.getY(),1,-1,austinYMap,-austinYMap);
    		case "testing":	
    			return map(gamePad.getY(),1,-1,testingYMap,-testingYMap);
    		case "threeaxis":
    			return map(threeAxis.getY(),1,-1,threeAxisYMap,-threeAxisYMap);
    		default :
    			return 0;
        	}
        }
    public double getAxisTranslate(){
        switch(driver.toLowerCase()){
    		case "jd":	
    			return map(gamePad.getX(),1,-1,jdXMap,-jdXMap);
    		case "austin":	
    			return map(leftStick.getX(),1,-1,austinXMap,-austinXMap);
    		case "twodriver":
    			return map(leftStick.getX(),1,-1,austinXMap,-austinXMap);
    		case "testing":	
    			return map(gamePad.getX(),1,-1,testingXMap,-testingXMap);
    		case "threeaxis":
    			return map(threeAxis.getX(),1,-1,threeAxisXMap,-threeAxisXMap);
    		default :
    			return 0;
        	}
        }
    public double getRotation(){
        switch(driver.toLowerCase()){
    		case "jd":	
    			return map(gamePad.getZ(),1,-1,jdZMap,-jdZMap);
    		case "austin":	
    			return map(rightStick.getX(),1,-1,austinZMap,-austinZMap);
    		case "twodriver":
    			return map(rightStick.getX(),1,-1,austinZMap,-austinZMap);
    		case "testing":	
    			return map(gamePad.getZ(),1,-1,testingZMap,-testingZMap);
    		case "threeaxis":
    			return map(threeAxis.getZ(),1,-1,threeAxisZMap,-threeAxisZMap);
    		default :
    			return 0;
        	}
    }
    
    public double getGyro(){
    	switch(driver.toLowerCase()){
    	case "jd":
    		return Robot.chassis.adjustedYaw();
    	case "austin":
    		return Robot.chassis.adjustedYaw();
    	case "twodriver":
    		return Robot.chassis.adjustedYaw();
    	case "testing":
    		return 0;
    	case "threeaxis":
			return 0;
    	default:
    		return 0;
    	}
    }
    
    private double map(double input, double maximum, double minimum, double outputMax, double outputMin){
    	double output = (input/(maximum-minimum)-minimum/(maximum-minimum))*(outputMax-outputMin)+outputMin;
    	return output; 
    	//NO ONE EXPECTS THE SPANISH INQUISITION
    	}
    
    public String getDriver(){
    	return driver.toLowerCase();
    }
        
    public OI(String new_driver){
    	driver=new_driver;
    	if(driver=="default"){
    		driver = "twodriver";
    	}
        SmartDashboard.putData("SetDriver(JD)", new SwitchDriver("jd"));
        SmartDashboard.putData("SetDriver(Austin)", new SwitchDriver("austin"));
        SmartDashboard.putData("SetDriver(Two Drivers)", new SwitchDriver("twodriver"));
        SmartDashboard.putData("SetDriver(Test Mode)", new SwitchDriver("testing"));
    		
    	switch(driver.toLowerCase()){
    		case "jd":
	    		gamePad = new Joystick(0);
		        
		        buttonG1  = new JoystickButton(gamePad,  1);
		        buttonG1.whenPressed(new BidentToggle());
		               
		        buttonG2  = new JoystickButton(gamePad,  2);
		        buttonG2.whenPressed(new RollersIn());
		        		        
		       // buttonG3  = new JoystickButton(gamePad,  3);
		       // buttonG3.whenPressed(new ToteStack());
		        
		        buttonG4  = new JoystickButton(gamePad,  4);
		        buttonG4.whenPressed(new RollersOut());
		        	        
		        buttonG5  = new JoystickButton(gamePad,  5);
		        buttonG5.whileHeld(new BidentSetVelocity(100));
		        buttonG5.whenReleased(new BidentSetVelocity(0));
		        
		        buttonG6  = new JoystickButton(gamePad,  6);
		        //buttonG6.whenPressed(new ToteUp());
		        		        
		        buttonG7  = new JoystickButton(gamePad,  7);
		        buttonG5.whileHeld(new BidentSetVelocity(-100));
		        buttonG5.whenReleased(new BidentSetVelocity(0));
		        		        
		        buttonG8  = new JoystickButton(gamePad,  8);
		        //buttonG8.whenPressed(new ToteDown());
		        		        
		        buttonG9  = new JoystickButton(gamePad,  9);
		        
		        
		        buttonG10 = new JoystickButton(gamePad, 10);
		        
		        
		        
		    break;
		    
    		case "austin":
        		leftStick = new Joystick(0);
    	        
    	        buttonL1  = new JoystickButton(leftStick,  1);
    	        buttonL1.whenPressed(new BidentToggle());
    	               
    	        buttonL2  = new JoystickButton(leftStick,  2);
    	        buttonL2.whileHeld(new BidentDown());
    	
    	        buttonL3  = new JoystickButton(leftStick,  3);
    	        buttonL3.whileHeld(new BidentUp());
    	        
    	        buttonL4  = new JoystickButton(leftStick,  4);
    	        
    	        
    	        buttonL5  = new JoystickButton(leftStick,  5);
    	        
    	        
    	        buttonL6  = new JoystickButton(leftStick,  6);
    	        
    	        
    	        buttonL7  = new JoystickButton(leftStick,  7);
    	        
    	        
    	        buttonL8  = new JoystickButton(leftStick,  8);
    	        
    	        
    	        buttonL9  = new JoystickButton(leftStick,  9);
    	        
    	        
    	        buttonL10 = new JoystickButton(leftStick, 10);
    	        
    	        
    	        rightStick = new Joystick(1);
    	        
    	        buttonR1 = new JoystickButton(rightStick,   1);
    	        buttonR1.whenPressed(new ToteStack());
    	
    		    buttonR2 =  new JoystickButton(rightStick,  2);
    		    buttonR2.whenPressed(new ToteDown());
    		    
    		    buttonR3 =  new JoystickButton(rightStick,  3);
    		    buttonR3.whenPressed(new ToteUp());
    		    
    		    buttonR4 =  new JoystickButton(rightStick,  4);
    	        buttonR4.whenPressed(new RollersIn());
    	        
    	        buttonR5 =  new JoystickButton(rightStick,  5);
    	        buttonR5.whenPressed(new RollersOut());
    	        
    	        buttonR6  = new JoystickButton(rightStick,  6);
    	        
    	        
    	        buttonR7  = new JoystickButton(rightStick,  7);
    	        
    	        
    	        buttonR8  = new JoystickButton(rightStick,  8);
    	        
    	        
    	        buttonR9  = new JoystickButton(rightStick,  9);
    	        
    	        
    	        buttonR10 = new JoystickButton(rightStick, 10);
    	        
    	        
    	    break;
    		
    		case "twodriver":
    			gamePad = new Joystick(0);
    			leftStick = new Joystick(1);
    			rightStick = new Joystick(2);
    			
		        buttonG1  = new JoystickButton(gamePad,  1);
		        buttonG1.whenPressed(new BidentToggle());
		               
		        buttonG2  = new JoystickButton(gamePad,  2);
		        buttonG2.whenPressed(new RollersIn());
		        		        
		       // buttonG3  = new JoystickButton(gamePad,  3);
		       // buttonG3.whenPressed(new ToteStack());
		        
		        buttonG4  = new JoystickButton(gamePad,  4);
		        buttonG4.whenPressed(new RollersOut());
		        	        
		        buttonG5  = new JoystickButton(gamePad,  5);
		        buttonG5.whileHeld(new BidentSetVelocity(200));
		        buttonG5.whenReleased(new BidentSetVelocity(0));
		        
		        buttonG6  = new JoystickButton(gamePad,  6);
		        buttonG6.whileHeld(new ToteSetVelocity(200));
		        buttonG6.whenReleased(new ToteSetVelocity(0));
		        
		        buttonG7  = new JoystickButton(gamePad,  7);
		        buttonG7.whileHeld(new BidentSetVelocity(-200));
		        buttonG7.whenReleased(new BidentSetVelocity(0));
		        		        
		        buttonG8  = new JoystickButton(gamePad,  8);
		        buttonG8.whileHeld(new ToteSetVelocity(-200));
		        buttonG8.whenReleased(new ToteSetVelocity(0));
		        		        
		        buttonG9  = new JoystickButton(gamePad,  9);
		        
		        
		        buttonG10 = new JoystickButton(gamePad, 10);
		    
    	    
    	    
    		case "testing":
    			gamePad = new Joystick(0);
    			
		        
		        buttonG1  = new JoystickButton(gamePad,  1);
		        buttonG1.whenPressed(new ToteStop());
		               
		        buttonG2  = new JoystickButton(gamePad,  2);
		        buttonG2.whenPressed(new RollersOut());
		        //buttonG2.whenReleased(new BidentStop());
		        
		        buttonG3  = new JoystickButton(gamePad,  3);
		        buttonG3.whenPressed(new BidentStop());
		        
		        buttonG4  = new JoystickButton(gamePad,  4);
		        buttonG4.whenPressed(new RollersIn());
		        //buttonG4.whenReleased(new BidentStop());		        		
		        
		        buttonG5  = new JoystickButton(gamePad,  5);
		        buttonG5.whenPressed(new BidentUp());
		        //buttonG5.whenReleased(new BidentStop());
		        
		        buttonG6  = new JoystickButton(gamePad,  6);
		        buttonG6.whenPressed(new ToteUp());
		        //buttonG6.whenReleased(new ToteStop());
		        
		        buttonG7  = new JoystickButton(gamePad,  7);
		        buttonG7.whenPressed(new BidentDown());
		        //buttonG7.whenReleased(new BidentStop());
		        
		        buttonG8  = new JoystickButton(gamePad,  8);
		        buttonG8.whenPressed(new ToteDown());
		        //buttonG8.whenReleased(new ToteStop());
		        
		        buttonG9  = new JoystickButton(gamePad,  9);
		        buttonG9.whenPressed(new BidentToggle());
		        
		        buttonG10 = new JoystickButton(gamePad, 10);
		        //buttonG10.whenPressed(new BidentHoming());    	        
    	        

    		break;
    		
    		case "threeaxis":
    			threeAxis = new Joystick(0);
    		
    	}    
	        
    }    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
 }

